---
title: 'Tidy Tuesday #1'
author: "Audrey Smyczek"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
theme_set(theme_minimal()) # My favorite ggplot() theme :)
```

## Dog Breed Data

```{r}
# Read in the data for the week
breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv')
trait_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/trait_description.csv')
breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv')
```

This week's data is about Dog Breeds. Read more about it, including definitions of variables, [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-02-01/readme.md). 


```{r}
breed_rank_all %>% 
  select(`Breed`:`2020 Rank`) %>% 
  filter(`2020 Rank` < 20) %>% 
  ggplot()+
    geom_point(aes(x=`2020 Rank`, y=`2015 Rank`,color = "2015"))+
    geom_point(aes(x=`2020 Rank`, y=`2016 Rank`,color = "2016"))+
    geom_point(aes(x=`2020 Rank`, y=`2017 Rank`,color = "2017"))+
    geom_point(aes(x=`2020 Rank`, y=`2018 Rank`,color = "2018"))+
    geom_point(aes(x=`2020 Rank`, y=`2019 Rank`,color = "2019"))+
  labs(x="2020 Rank",
       y = "Past Rank",
       title="Correlation of Rank from Past Years to 2020",
       caption="Plot created by Audrey Smyczek, data from American Kennel Club")+
  theme_classic()
```


