---
title: 'Tidy Tuesday #3'
author: "Audrey Smyczek"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
theme_set(theme_minimal()) # My favorite ggplot() theme :)
```

## Data choice 2: Alternative fuel stations

```{r}
stations <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-01/stations.csv')
```


```{r, fig.height= 9, fig.width= 9, fig.alt="The column graph shows the number of alternative fuel stations by state. The colors of the bars are mostly turquoise, which signify that the station is public, but all states have a small sliver of orange, proportional to the overall column. The amount of orange siginifies the number of stations that are private. The graph shows that California has the largest number with close to 15000 stations. There is a large drop in numbers of stations, following California is New York with around 2500 stations."}
stations %>% 
  select(`CITY`, `STATE`, `ACCESS_CODE`) %>% 
  group_by(`STATE`, `ACCESS_CODE`) %>%
  summarise(NUM_BY_STATE = n()) %>%
  arrange(`STATE`) %>% 
  ggplot(aes(y = fct_reorder(`STATE`, `NUM_BY_STATE`, sum), x = `NUM_BY_STATE`))+
  geom_col(aes(fill = `ACCESS_CODE`))+
  labs(title =  "Number of Alternative Fuel Station by State", x = NULL, y = "State",
       caption = "Plot created by Audrey Smyczek.\n Data from https://afdc.energy.gov/data_download/alt_fuel_stations_format.")+
  theme(plot.title = element_text(size = 10,
                                  hjust = 0.5,
                                  face = "bold"),
        plot.caption = element_text(size = 8,
                                    hjust = 0.5),
        panel.grid.major = element_blank())

```

